### PR TITLE
49 api for log in or not

### LINKED ISSUE #49: api for log in or not

### PR DESCRIPTION
**Pull request by harshkumbhani**
# Added LOGGED_IN field in the user data model

1. Default is False
2. Sets to True when user registers or logs in
3. Sets to False when user logs out.

- Same data returned from get_user_data api, 

```
{
    "detail": "User data",
    "username": "harsh",
    "user_id": 1,
    "mfa_enable_flag": false,
    "logged_in": true,
    "profile_picture": null
}
```

### CODE REVIEW

**Review by vivilenard — APPROVED** [review]
looks good

**Comment by RealConrad** [comment]
What is the point of this feature?

**Comment by vivilenard** [comment]
> What is the point of this feature?

to get all user data at once

**Comment by vivilenard** [comment]
harsh said adding logged_in bool is good proof to know if user is logged in. seems easy then

**Comment by RealConrad** [comment]
But why? That is the entire purpose for jwt tokens. To authenticate users, if users do not have valid tokens --> not logged in.

Also using a boolean value like that is unreliable. You set it to true if they log in, but what if they never logout and their tokens expire?? If we use that boolean value for some logic check, that would cause problems in that case.

**Comment by vivilenard** [comment]
Okay, so I will check for access token then

**Comment by RealConrad** [comment]
Why do you need to check if a user is logged in or not?

**Comment by vivilenard** [comment]
Why would I not? I cannot make it dependent on the event of the login. If I reload the page, I need to know if he is logged in so I can display name and profile picture

**Comment by RealConrad** [comment]
Yes so - if the function I made to refresh the token returns 200 - they are considered logged in. If it returns an error - they should be considered logged out

**Pull request merged**
