### PR TITLE
Frontend/login

### PR DESCRIPTION
**Pull request by vivilenard**
# Added login / register page

Bildschirmfoto 2024-07-22 um 09 04 35
Bildschirmfoto 2024-07-22 um 09 05 33

### CODE REVIEW

**Comment by kglebows** [comment]
@vivilenard, its different from the FIGMA design and colors are off, why?

Also the native bootstrap modals look nice and easy to implement (with adjustments to Figma design) https://getbootstrap.com/docs/5.3/examples/modals/

**Comment by vivilenard** [comment]
Its not perfect yet, i just wanted to create the basics so that we can connect it to backend and see if it works.

**Comment by vivilenard** [comment]
It's better now. I think it's quite close to figma design?
Screen Shot 2024-07-22 at 12 10 15 PM
Screen Shot 2024-07-22 at 12 09 43 PM

**Comment by kglebows** [comment]
@vivilenard Better, but the font is different and text smaller? on main layer primary font is `Press Start 2P` and secondary is `Inter`
If u want to introduce third font that is ok, but more fonts may cast whole universe into madness of chaos so tread carefully..

Also, Add 42 logo to a button, it looks cool. 

Also, according to studies SIGN IN and SIGN UP are way better than Register, Login, join etc. (https://ux.stackexchange.com/questions/1080/using-sign-in-vs-using-log-in)

Im strict because the idea is to submit PR with finished or almost finished (but completed in next PR) stuff so that we dont have to return to it later. Most likely what is submitted in a PR and works will go into production, so it is vital to maintain quality closer to final. Thats also why first we design in Figma, so that we have clear guidance what we want to achieve.

**Comment by RealConrad** [comment]
no idea whats going on here, but PR has open for months now with no activity, so assuming its not needed anymore

**Pull request closed without merging**
