### PR TITLE
Frontend/display name

### PR DESCRIPTION
**Pull request by vivilenard**
Bildschirmfoto 2024-12-13 um 15 16 23

displays custom name

### CODE REVIEW

**Review by RealConrad — CHANGES_REQUESTED** [review]
Change it to use the display name in each game setup component, both normal + tournament. Should prepopulate the input field for user

If you're not sure how, I will do it over the weekend then

**Comment by vivilenard** [comment]
Bildschirmfoto 2024-12-13 um 16 31 15
ok. username is v, display name is vivi -->
Bildschirmfoto 2024-12-13 um 16 33 00
Bildschirmfoto 2024-12-13 um 16 32 12
Bildschirmfoto 2024-12-13 um 16 37 10

Changed it like this. Thats what you meant?

**Comment by harshkumbhani** [comment]
Yeah seems good!

**Review by harshkumbhani — APPROVED** [review]
LGTM )

**Review by RealConrad — APPROVED** [review]

**Pull request merged**
