### PR TITLE
Game design

### PR DESCRIPTION
**Pull request by vivilenard**
Bildschirmfoto 2024-06-28 um 18 28 35
The game is visible, it detects the keystrokes.
Now we need to see how i can communicate with backend for serverside pong.

### CODE REVIEW

**Comment by RealConrad** [comment]
Looks great, however a couple of things:
- Current implementation does not replicate Figma? @kglebows 
- All game logic will be handled on the backend such as ball movement/direction / paddles etc.
- All frontend has to do is basically just draw at cords that backend will send
- We will need a screen before the game itself for waiting in a queue (e.g. 1 player would maybe have to wait 20seconds before finding a match as there would be no players at that time - how do we display this?)
- I am busy creating a super basic `pong.js` file that will include how to setup stuff up to communicate with server

**Comment by vivilenard** [comment]
yes i can make it look more like figma. But I think we need a frame around it. If the game frame is smaller than the actual window it doesnt really look good:
Bildschirmfoto 2024-06-28 um 22 13 24
This would be an option:
Bildschirmfoto 2024-06-28 um 22 21 27

**Comment by RealConrad** [comment]
Yes, i agree i current figma design needs improvements for such cases and needs to be more "fleshed out".

However, I then think it would be best to first decide on a design before implementing more content in that case as we would be then just re-doing work, no?

Not sure what the progress on the figma designs @kglebows @vivilenard  

I did say i wouldn't really contribute much to the frontend part, however i do feel that everyone working on the frontend is a bit to "disconnected". Maybe its just me. @vivilenard @kglebows @PetruCazac

**Comment by kglebows** [comment]
The idea is that all u need to establish a gamearea is two paddles and a straight line in a middle. The top and bottom end of line marks the top and bottom walls that the ball will bounce from. I would wait with redesigning after making and testing working basic game to actually get the gameplay feedback. I was a bit sick and busy last two weeks, but next week I will connect back :D 

Also @vivilenard can we make canvas stretchable? The game resolution will be fixed but view could be scalable in any direction fixed to a window. So for wider screens it would just make a game wider without actually breaking the gameplay.

**Comment by kglebows** [comment]
On Figma I made a separate view where I'm developing the rest of screens, what's left to design is last option (account or settings, I will prepare two versions) and account management, profile view with match history and so on. I will also prepare two versions, one embedded within original design and one with top layer. I will post link on slack in few minutes

**Review by kglebows — DISMISSED** [review]
good start for canvas

**Comment by kglebows** [comment]
Ok so i did update here xD im still working on it but added a lot of improvements. u can check current version here -> https://miniature-space-happiness-ww5r4vw545p3g7px-443.app.github.dev/

**Comment by kglebows** [comment]
image

implemented a lot of changes to CSS and JS. made it look more like Figma project.
Added button description text.

Animated paddles, animated cursor, animated highlights 
image

Paddles follow the cursor on the left and right side.
Paddles stick to options.
Left side mousovers open right side panels
Highlights stay when right side is opened 
Ball (cursor) has trail indicating movement direction
Ball is getting excited when clickable option encountered (now it works on left side but in final version it will interact only with right side items as left side is mousover only in main menu)
Highlight is an animation of bigger/smaller glows 


Dynamic screen change added (right side is still broken, but left works as intended) 

Auto adjustable resolution for maintaining 16x9 game area. when less then 720p height it goes into only game mode (without header and footer) with fixed size (minimum game size is 720p) 
image

Added NGNIX minor fix for running CSS and JS.

**Review by kglebows — APPROVED** [review]
Amazing! BEST CODE EVER!

**Review by RealConrad — APPROVED** [review]

**Pull request merged**
